game_director_task:
  description: >
    Define the creative vision, core concept, and high-level direction for the {game} prototype. Set clear objectives and constraints for the team to ensure a unified vision.
  expected_output: >
    A concise vision statement, core concept summary, and a list of objectives and constraints for the {game} prototype.
  agent: game_director

game_designer_task:
  description: >
    Design the core gameplay mechanics, rules, and systems for the {game} prototype based on the vision and objectives. Create a basic gameplay loop and outline key features.
  expected_output: >
    A detailed description of the core gameplay mechanics, rules, systems, and a basic gameplay loop for the {game} prototype, including a list of key features.
  agent: game_designer

game_developer_task:
  description: >
    Implement a technical plan for the {game} prototype, outlining the architecture, tools, and technologies to be used. Provide a step-by-step plan for rapid prototyping and testing.
  expected_output: >
    A technical implementation plan for the {game} prototype, including architecture, tools, technologies, and a step-by-step prototyping and testing plan.
  agent: game_developer
